name: turborepo-remote-cache-js
description: 'run turborepo-remote-cache server with JavaScript'
inputs:
  port:
    required: false
    description: "server port"
    default: "3000"
  google_cloud_project:
    required: true
    description: "google cloud project"
  google_application_credentials:
    required: true
    description: "google application credentials"
  storage_path:
    required: true
    description: "storage path"
runs:
  using: 'node20'
  main: 'dist/index.js'

