name: turborepo-remote-cache
description: "run turborepo-remote-cache server"
inputs:
  port:
    required: false
    description: "server port"
    default: "3000"
  google_cloud_project:
    required: true
    description: "google cloud project"
  google_application_credentials:
    required: true
    description: "google application credentials"
  storage_path:
    required: true
    description: "storage path"
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "TURBO_API=http://localhost:${{ inputs.port }}" >> $GITHUB_ENV
        echo "TURBO_TEAM=${{ github.event.repository.name }}" >> $GITHUB_ENV
        echo "TURBO_TOKEN=turbo_token" >> $GITHUB_ENV

    - uses: pnpm/action-setup@v3
      with:
        version: 10
        package_json_file: "${GITHUB_ACTION_PATH}/package.json"

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - shell: bash
      run: pnpm exec turborepo-remote-cache &
      env:
        PORT: ${{ inputs.port }}
        STORAGE_PROVIDER: "google-cloud-storage"
        STORAGE_PATH: ${{ inputs.storage_path }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ inputs.google_application_credentials }}

    - shell: bash
      run: |
        echo "Waiting for server to become healthy..."
        sleep 1
        for i in {1..10}; do
          status=$(curl -s -o /dev/null -w "%{http_code}" "${TURBO_API}/v8/artifacts/status" || echo "000")
          echo "Attempt $i: Received status code $status"
          if [ "$status" -eq 200 ]; then
            echo "Server is healthy."
            exit 0
          fi
          echo "Server not yet healthy. Retrying in 1 seconds..."
          sleep 1
        done
        echo "Server health check failed after 10 attempts."
        exit 1

