name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TURBO_API: ${{ secrets.TURBO_API }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
    - name: Check out code
      uses: 'actions/checkout@v4'

    - uses: pnpm/action-setup@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
 
    - name: Install dependencies
      run: pnpm install

    - name: Lint
      run: pnpm lint
 
    - name: Build
      run: pnpm build
 
