name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      TURBO_API: ${{ secrets.TURBO_API }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
    - name: Check out code
      uses: 'actions/checkout@v4'
    
    - uses: 'google-github-actions/auth@v2'
      id: auth
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}

    - run: echo "TURBO_TOKEN=${{ steps.auth.outputs.id_token }}" >> $GITHUB_ENV

    - uses: pnpm/action-setup@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
 
    - name: Install dependencies
      run: pnpm install

    - name: Lint
      run: pnpm lint
 
    - name: Build
      run: pnpm build
 
