name: CI (GitHub Actions)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      TURBO_API_PORT: 3000

    steps:
    - name: Check out code
      uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      id: auth
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}

    - uses: pnpm/action-setup@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
 
    - name: Install dependencies
      run: pnpm install

    - name: Run turborepo-remote-cache
      run: npx turborepo-remote-cache --yes & sleep 5
      env:
        TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        PORT: ${{ env.TURBO_API_PORT }}
        STORAGE_PROVIDER: 'google-cloud-storage'
        STORAGE_PATH: ${{ secrets.STORAGE_PATH }}

    - name: Lint
      run: pnpm lint
 
    - name: Build
      run: pnpm build
      env:
        TURBO_API: 'http://localhost:${{ env.TURBO_API_PORT }}'
        TURBO_TEAM: ${{ env.TURBO_TEAM }}
        TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
 
