name: CI (GitHub Actions)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      TURBO_API: "http://localhost:3000"
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

    steps:
    - name: Check out code
      uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      id: auth
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}

    - uses: pnpm/action-setup@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Run turborepo-remote-cache
      run: npx turborepo-remote-cache@2.2.12
      env:
        STORAGE_PROVIDER: 'google-cloud-storage'
        STORAGE_PATH: ${{ secrets.STORAGE_PATH }}

    - name: Health check
      run: |
        echo "Waiting for server to become healthy..."
        for i in {1..10}; do
          response=$(curl -s -o /dev/null -w "%{http_code}" "${ TURBO_API }/v8/artifacts/status")
          echo "Attempt $i: Received status code $status"
          if [ "$status" -eq 200 ]; then
            echo "Server is healthy."
            exit 0
          fi
          echo "Server not yet healthy. Retrying in 5 seconds..."
          sleep 5
        done
        echo "Server health check failed after 10 attempts."
        exit 1

    - name: Install dependencies
      run: pnpm install

    - name: Lint
      run: pnpm lint
 
    - name: Build
      run: pnpm build
 
